# Generated by Django 5.1.2 on 2025-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_added',
            field=models.DateField(),
        ),
    ]
